language: python

python:
  - "2.6"
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install -q coverage coveralls --use-wheel
script:
  - py.test --cov=puppetboard --pep8  -v
  - ./bandit.sh

after_success:
  - coveralls
